/* AUTOGENERATED FILE - SAFE VERSION FOR sw_contactform_2026 */

/* Table schema:
CREATE TABLE sw_contactform_2026 (
  key TEXT NOT NULL PRIMARY KEY,
  value JSONB NOT NULL
);
*/

import { createClient } from "jsr:@supabase/supabase-js@2.49.8";

const TABLE = "sw_contactform_2026";

const client = () =>
  createClient(
    Deno.env.get("SUPABASE_URL")!,
    Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,
  );

/* ----------------------------------------
   Types (Contact Form structure)
----------------------------------------- */
export type ContactForm = {
  full_name: string;
  email: string;
  phone?: string;
  message: string;
  created_at?: string;
};

/* ----------------------------------------
   Basic KV operations
----------------------------------------- */

// Set single value
export const set = async (
  key: string,
  value: any,
): Promise<void> => {
  const supabase = client();

  const { error } = await supabase
    .from(TABLE)
    .upsert({ key, value });

  if (error) throw new Error(error.message);
};

// Get single value
export const get = async (key: string): Promise<any> => {
  const supabase = client();

  const { data, error } = await supabase
    .from(TABLE)
    .select("value")
    .eq("key", key)
    .maybeSingle();

  if (error) throw new Error(error.message);
  return data?.value;
};

// Delete single value
export const del = async (key: string): Promise<void> => {
  const supabase = client();

  const { error } = await supabase
    .from(TABLE)
    .delete()
    .eq("key", key);

  if (error) throw new Error(error.message);
};

/* ----------------------------------------
   Multiple operations
----------------------------------------- */

// Set multiple
export const mset = async (
  keys: string[],
  values: any[],
): Promise<void> => {
  const supabase = client();

  const rows = keys.map((k, i) => ({
    key: k,
    value: values[i],
  }));

  const { error } = await supabase.from(TABLE).upsert(rows);

  if (error) throw new Error(error.message);
};

// Get multiple
export const mget = async (keys: string[]): Promise<any[]> => {
  const supabase = client();

  const { data, error } = await supabase
    .from(TABLE)
    .select("value")
    .in("key", keys);

  if (error) throw new Error(error.message);
  return data?.map((d) => d.value) ?? [];
};

// Delete multiple
export const mdel = async (keys: string[]): Promise<void> => {
  const supabase = client();

  const { error } = await supabase
    .from(TABLE)
    .delete()
    .in("key", keys);

  if (error) throw new Error(error.message);
};

/* ----------------------------------------
   Search helpers
----------------------------------------- */

// Get values by key prefix
export const getByPrefix = async (
  prefix: string,
): Promise<any[]> => {
  const supabase = client();

  const { data, error } = await supabase
    .from(TABLE)
    .select("key, value")
    .like("key", `${prefix}%`);

  if (error) throw new Error(error.message);
  return data?.map((d) => d.value) ?? [];
};

/* ----------------------------------------
   Contact Form helper (recommended)
----------------------------------------- */

// Save contact form submission
export const saveContact = async (
  form: ContactForm,
): Promise<void> => {
  const key = `contact_${Date.now()}`;

  const value = {
    ...form,
    created_at: new Date().toISOString(),
  };

  await set(key, value);
};