/**
 * Shared portfolio/realizacje data for main page section and /realizacje page.
 */
export const PORTFOLIO_ITEMS = [
  {
    title: 'Wrocław Walks',
    category: 'Web Development',
    description: 'Strona dla przewodnika miejskiego z ofertą wycieczek pieszych po Wrocławiu, kalendarzem i rezerwacją',
    image: '/assets/wroclaw-walks-cover.png',
    gradient: 'from-emerald-500 to-teal-600',
    link: 'https://cork-merge-98211723.figma.site/',
  },
  {
    title: 'Gōsei',
    category: 'Web Development',
    description: 'Ekskluzywny sklep z diamentami hodowanymi w laboratorium, z minimalistycznym designem i pełnym procesem zakupowym',
    image: '/assets/gosei-cover.png',
    gradient: 'from-rose-900 to-red-800',
    link: 'https://gosei-diamond.lovable.app/#poczatek',
  },
  {
    title: 'Kepller',
    category: 'Web Development',
    description: 'Profesjonalna strona dla firmy telekomunikacyjnej z nowoczesnym designem i strukturą',
    image: '/assets/kepller-cover.png',
    gradient: 'from-slate-500 to-zinc-600',
    link: 'https://kepllerpage.vercel.app/',
  },
  {
    title: 'OrthoMedica',
    category: 'Web Development',
    description: 'Nowoczesna strona brandowa z unikalnym designem, premium animacjami i UX',
    image: '/assets/orthomedica-cover.png',
    gradient: 'from-purple-500 to-pink-500',
    link: 'https://orthomedicav5.figma.site/',
  },
  {
    title: 'OrthoMedica - Klinika',
    category: 'Web Development',
    description: 'Alternatywna wersja strony kliniki ortodontycznej dla dzieci i dorosłych',
    image: '/assets/orthomedica-v4-cover.png',
    gradient: 'from-indigo-600 to-blue-900',
    link: 'https://orthomedicav4.figma.site',
  },
  {
    title: 'Maison - Baked with Soul',
    category: 'Web Development',
    description: 'Elegancka strona dla piekarni z artystyczną prezentacją produktów i ciepłą atmosferą',
    image: '/assets/maison-cover.png',
    gradient: 'from-amber-500 to-orange-500',
    link: 'https://maisonbakery.figma.site/',
  },
  {
    title: 'SmartWeave Studio',
    category: 'Web Development',
    description: 'Studio automatyzacji i stron internetowych - własna wizytówka SmartWeave',
    image: '/assets/smartweave-studio-cover.png',
    gradient: 'from-lime-400 to-slate-900',
    link: 'https://smartweave.pl/',
  },
  {
    title: 'DentalMint',
    category: 'Web Development',
    description: 'Nowoczesna strona brandowa z unikalnym designem, premium animacjami i UX',
    image: '/assets/dentalmint-cover.png',
    gradient: 'from-teal-400 to-emerald-600',
    link: 'https://dentalmint.figma.site',
  },
  {
    title: 'AIYO',
    category: 'Web Development',
    description: 'Agencja łącząca AI automation, design stron i vibe coding - dla firm, które chcą skalować',
    image: '/assets/aiyo-cover.png',
    gradient: 'from-cyan-500 to-blue-500',
    link: 'https://aiyo.figma.site/',
  },
  {
    title: 'Lumière',
    category: 'Web Development',
    description: 'Elegancka strona dla salonu urody premium z eleganckim designem i prezentacją usług',
    image: '/assets/lumiere-cover.png',
    gradient: 'from-amber-200 to-stone-400',
    link: 'https://deaf-broil-44422386.figma.site/',
  },
] as const;
